server:
  port: 0
spring:
  application:
    name: microservice-message-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
### 参考：https://spring.io/guides/gs/client-side-load-balancing/